### ISSUE TITLE
Lemmas of stdlib interest

### ISSUE THREAD

**Issue by mrhaandi** [uds-psl/coq-library-undecidability#118]
Not truly an issue, but something worth to mention:
in some of my proofs I use ad-hoc lemmas, e.g. showing `Forall P (map f l) <-> Forall (fun x => P (f x)) l.` which clearly should be part of the Coq standard library. Therefore, I requested https://github.com/coq/coq/pull/13955 for the worst offenders. Hopefully, this will further improve upon the separation of concerns aspect in the undecidability library.

**Comment by DmxLarchey** [comment]
Yes there were and still are many missing lemmas about `Forall`, `Forall2`, `In` etc in the stdlib. The `Forall_map` you mention above has been living in my own shared lib [`Shared/Libs/DLW/Utils/utils_list.v`](https://github.com/uds-psl/coq-library-undecidability/blob/a9d60eaa44cbf8d0ba44227a13ed0dea173e8b28/theories/Shared/Libs/DLW/Utils/utils_list.v#L835) since CPP19... but is far older than that. They are truckloads of other examples. Maybe finding suitable names is the issue within the stdlib?

**Comment by mrhaandi** [comment]
Since I started using Coq, stdlib was the single most stable piece of code that I know of (probably due to the rigorous ci).
Probably it is a difficult task to juggle lemmas that are truly of general interest (which I would assume for homomorphic interactions between two notions in `List.v`) and some special purpose lemmas (which may pollute stdlib in the long run).
Anyway, I think it is good to rely on stdlib to make the undecidability library code more lightweight. My suggested lemmas also seem to fit nicely within its current scope.

**Comment by mrhaandi** [comment]
I also suggested (https://github.com/coq/coq/pull/14008) the most rudimentary Cantor pairing to be part of stdlib.

**Comment by mrhaandi** [comment]
Both mentioned PRs are merged into Coq `master` and will be part of `8.14`. I'm looking forward to remove some boilerplate from my proofs.
Maybe it is worthwhile to consider which parts of `Shared` are also of general interest (improving the standard library) and make our code more lightweight.

PS: while writing some compatibility code for other Coq CI projects most of the code that broke was redundant wrt. the standard library. It is kept around because of full backwards compatibility. Our branch system does not suffer from such a limitation.

PPS: https://github.com/coq/coq/issues/6459 could be an opportunity to properly implement vectors.
