### ISSUE TITLE
Confusing branches

### ISSUE THREAD

**Issue by mrhaandi** [uds-psl/coq-library-undecidability#73]
There are some stale branches like `update-readme`, `trakh_dominik`, or `yforster-travis_for_wip` that somewhat disturb the overall branch structure, i.e. `coq-8.12`, `coq-8.11`, etc.
I suggest those branches to be either moved to private forks (work via pull requests) or deleted to keep the branch structure clean.

**Comment by yforster** [comment]
I deleted `count_states_haskell`, `update-readme` and `yforster-travis_for_wip`.

@dominik-kirst @DmxLarchey what's the status of `trakh_full`,`trakthenbrot_ijcar` and `trakh_dominik`? Given the [webpage](https://www.ps.uni-saarland.de/extras/fol-trakh/) of the project and that the results are merged to the library, are the other branches still needed?

`master` can be deleted, do you agree @DmxLarchey @mrhaandi?

What's the status of `informative_lift` @DmxLarchey? The corresponding PR #27 is closed. Maybe we can move the branch to your private fork as Andrej suggests? Similarly, `my_own_tapes` was just for discussion, maybe we can move it to your fork as well?

Afterwards we'd be down to `coq-8.12`, `coq-8.11`, `coq-8.10` and `noopam` (the latter becoming potentially obsolete in the near future once coq/platform takes off).

**Comment by mrhaandi** [comment]
> `master` can be deleted

Either that or renamed to `coq-8.9`.

**Comment by DmxLarchey** [comment]
@yforster @mrhaandi I did copy the references to `my_own_tapes` and `informative_lift` to my own fork and then removed them from the main `uds-psl` git repo. 

The `trakthenbrot_ijcar` branch is hyper-linked twice in the IJCAR paper (beginning of the Discussion section 7) so removing it would somehow be problematic. I realize now that it was not a good idea to refer to a `branch` of a living repo. Maybe it would have been better to refer to a `tag` instead. I do not know if it is possible to move the `branch` name to a `tag` name without breaking the below http links:

- https://github.com/uds-psl/coq-library-undecidability/tree/trakhtenbrot_ijcar/theories/TRAKHTENBROT
- https://github.com/uds-psl/coq-library-undecidability/tree/trakhtenbrot_ijcar/theories/Shared/Libs/DLW

If possible I will do it and then the `tag` `trakhtenbrot_ijcar` will be less visible than the `branch` `trakhtenbrot_ijcar`.
Otherwise, if would prefer if we keep that branch for some time, because of the IJCAR paper.

Concerning, `trakh_full` and `trakh_dominik`, I did copy them to my own fork as well. However, since I did work on them with @dominik-kirst, I will wait for his green light to remove them from `uds-psl`. 

@dominik-kirst, you can either copy the refs to your own fork as well or else we can share those on one of our forks. However, they are mostly stalled now if think.

**Comment by dominik-kirst** [comment]
Green light for removing `trakh_full` and `trakh_dominik`.

**Comment by mrhaandi** [comment]
> Maybe it would have been better to refer to a `tag` instead.

As a side note, I discussed with Yannick that `tag`-based references are a future-proof mechanism in future papers that do not pollute the overall repository structure. This also at some point should be discussed and done uniformly, e.g. in a `year-conference-topic` style.

**Comment by DmxLarchey** [comment]
Ok the `tag` works, ie the former outside references still work with the `tag` instead of the `branch`. Hence, I will remove the `branch` reference for the official repo. 

Btw, tags are automatically converted to releases which is maybe not optimal...

**Comment by mrhaandi** [comment]
> > `master` can be deleted, do you agree @DmxLarchey @mrhaandi?
> 
> Either that or renamed to `coq-8.9`.

Now the only branch that might be misunderstood is `master`, which oftentimes signifies the main branch.
Is there a reason not to rename it to `coq-8.9` to retain the project's origin?
Afterwards, this issue can be closed.

**Comment by yforster** [comment]
I renamed `master` to `coq-8.9`. Thanks Andrej for poking us, the repo looks a lot tidier now!
